version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - '3009:3000'
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    networks:
     - test
  redis:
    image: redis:alpine
